name: weread bookmark sync

on:
  workflow_dispatch:
  schedule:
    - cron: "0,20,40 * * * *"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    env:
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
        FROM_PAGE: ${{ secrets.FROM_PAGE }}
        TO_PAGE: ${{ secrets.TO_PAGE }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: weread bookmark sync
        run: |
          python -u scripts/sync.py
      - name: Set up secret file
        env:
          FROM_PAGE: ${{ secrets.FROM_PAGE }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          TO_PAGE: ${{ secrets.TO_PAGE }}
        run: |
          echo $FROM_PAGE >> secrets.txt
          echo $NOTION_TOKEN >> secrets.txt
          echo $TO_PAGE >> secrets.txt
      - name: push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m 'add new heatmap' || echo "nothing to commit"
          git push || echo "nothing to push"